### ISSUE TITLE
is it possible to transliterate from gujarati language to hindi language? 

### ISSUE THREAD

**Issue by jaydangar** [narVidhai/Google-Transliterate-API#1]
I would like to know if it's possible to transliterate one language other than English to another language other than English?

**Comment by GokulNC** [comment]
Google unfortunately currently only supports Roman to native scripts.
For conversion from Indic script to Indic script, like Gujarati to Devanagari (Hindi), you can use the AksharaMukha library.

Installation:
```
pip install aksharamukha
```

Usage:
```py
from aksharamukha.transliterate import process
text = "ગુજરાતી મારી ભાષા છે."
result = process(text, 'Gujarati', 'Devanagari')
print(result) # "गुजराती मारी भाषा छे."
```

---

Or you can also use the [Indic NLP Library](https://anoopkunchukuttan.github.io/indic_nlp_library/)

**Comment by jaydangar** [comment]
Is there any specific library that i can port to flutter? I need a map for each and every language's unicode to another language's unicode. I am working for a library in dart programming language which basically transliterated from one language to another and for that I need a dataset of unicode mapping.

**Comment by jaydangar** [comment]
@GokulNC can you also let me know other than transliterating English to other languages, which languages are possible to convert from other languages to English? I have tested and saw that from hindi to English transliteration is possible.

**Comment by GokulNC** [comment]
For any Indic script to Indic script, you can use this code for porting:

https://github.com/anoopkunchukuttan/indic_nlp_library/blob/master/indicnlp/transliterate/unicode_transliterate.py

**Comment by GokulNC** [comment]
You can also check this to understand one to one mapping from any Indic script to any Indic script:

https://aksharamukha.appspot.com/describe/Gujarati

In the top right, you can choose any script to compare with Gujarati. Default is Roman script
